// Code generated by "shoot map -path=../../entity -way=<- -to=Envelope -type=Message"; DO NOT EDIT. (v0.7.1)

package dto

import "github.com/lopolopen/gap/internal/entity"

// FromEntity reads from type entity.Envelope, then writes back to receiver and returns it
func (m *Message) FromEntity(envelope_ *entity.Envelope) *Message {
	if envelope_ == nil {
		return nil
	}
	_m_ := NewMessage(
		"",                                    //ID
		m.TimeToDateTime(envelope_.CreatedAt), //CreatedAt
		envelope_.Version,                     //Version
		envelope_.Topic,                       //Topic
		envelope_.Group,                       //Group
		envelope_.Status,                      //Status
		"",                                    //Headers
		string(envelope_.Payload),             //Payload
		envelope_.Retries,                     //Retries
	)
	if m == nil {
		m = _m_
	} else {
		*m = *_m_
	}
	m.readEntity(envelope_)
	return m
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (m Message) ShootMap() { /*noop*/ }
