// Code generated by "shoot new -json -file=dto.go"; DO NOT EDIT. (v0.7.1)

package dto

import (
	"encoding/json"

	"github.com/lopolopen/gap/internal/entity"
	"github.com/lopolopen/gap/internal/enum"
	"github.com/lopolopen/gap/internal/pkgs/timex"
)

// NewPagedResult[T any] constructs a new instance of type PagedResult[T]
func NewPagedResult[T any](data []T, pagination *entity.Pagination) *PagedResult[T] {
	return &PagedResult[T]{
		Data:       data,
		Pagination: pagination,
	}
}

type _json_PagedResult[T any] struct {
	Data       []T                `json:"data"`
	Pagination *entity.Pagination `json:"pagination"`
}

// MarshalJSON serializes type PagedResult[T] to json bytes
func (p PagedResult[T]) MarshalJSON() ([]byte, error) {
	data := _json_PagedResult[T]{
		Data:       p.Data,
		Pagination: p.Pagination,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type PagedResult[T]
func (p *PagedResult[T]) UnmarshalJSON(data []byte) error {
	var pagedResult_ _json_PagedResult[T]
	if err := json.Unmarshal(data, &pagedResult_); err != nil {
		return err
	}
	p.Data = pagedResult_.Data
	p.Pagination = pagedResult_.Pagination
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p PagedResult[T]) ShootNew() { /*noop*/ }

// NewMeta constructs a new instance of type Meta
func NewMeta(typ enum.PluginKind, plugin enum.Plugin, version string) *Meta {
	return &Meta{
		Typ:     typ,
		Plugin:  plugin,
		Version: version,
	}
}

type _json_Meta struct {
	Typ     enum.PluginKind `json:"type"`
	Plugin  enum.Plugin     `json:"plugin"`
	Version string          `json:"version"`
}

// MarshalJSON serializes type Meta to json bytes
func (m Meta) MarshalJSON() ([]byte, error) {
	data := _json_Meta{
		Typ:     m.Typ,
		Plugin:  m.Plugin,
		Version: m.Version,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Meta
func (m *Meta) UnmarshalJSON(data []byte) error {
	var meta_ _json_Meta
	if err := json.Unmarshal(data, &meta_); err != nil {
		return err
	}
	m.Typ = meta_.Typ
	m.Plugin = meta_.Plugin
	m.Version = meta_.Version
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (m Meta) ShootNew() { /*noop*/ }

// NewMessage constructs a new instance of type Message
func NewMessage(id string, createdAt timex.DateTime, version string, topic string, group string, status enum.Status, headers string, payload string, retries int) *Message {
	return &Message{
		Mapper:    Mapper{},
		ID:        id,
		CreatedAt: createdAt,
		Version:   version,
		Topic:     topic,
		Group:     group,
		Status:    status,
		Headers:   headers,
		Payload:   payload,
		Retries:   retries,
	}
}

type _json_Message struct {
	ID        string         `json:"id"`
	CreatedAt timex.DateTime `json:"createdAt"`
	Version   string         `json:"version"`
	Topic     string         `json:"topic"`
	Group     string         `json:"group"`
	Status    enum.Status    `json:"status"`
	Headers   string         `json:"headers"`
	Payload   string         `json:"payload"`
	Retries   int            `json:"retries"`
}

// MarshalJSON serializes type Message to json bytes
func (m Message) MarshalJSON() ([]byte, error) {
	data := _json_Message{
		ID:        m.ID,
		CreatedAt: m.CreatedAt,
		Version:   m.Version,
		Topic:     m.Topic,
		Group:     m.Group,
		Status:    m.Status,
		Headers:   m.Headers,
		Payload:   m.Payload,
		Retries:   m.Retries,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Message
func (m *Message) UnmarshalJSON(data []byte) error {
	var message_ _json_Message
	if err := json.Unmarshal(data, &message_); err != nil {
		return err
	}
	m.ID = message_.ID
	m.CreatedAt = message_.CreatedAt
	m.Version = message_.Version
	m.Topic = message_.Topic
	m.Group = message_.Group
	m.Status = message_.Status
	m.Headers = message_.Headers
	m.Payload = message_.Payload
	m.Retries = message_.Retries
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (m Message) ShootNew() { /*noop*/ }

// NewMapper constructs a new instance of type Mapper
func NewMapper() *Mapper {
	return &Mapper{}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (m Mapper) ShootNew() { /*noop*/ }
