// Code generated by "shoot map -path=../../internal/entity -to=Envelope,Envelope -type=Published,Received"; DO NOT EDIT. (v0.7.1)

package xgorm

import "github.com/lopolopen/gap/internal/entity"

// ToEntity converts receiver to type entity.Envelope
func (p *Published) ToEntity() *entity.Envelope {
	if p == nil {
		return nil
	}
	envelope_ := new(entity.Envelope)
	envelope_.ID = p.ID
	envelope_.Version = p.Version
	envelope_.Topic = p.Topic
	envelope_.Payload = []byte(p.Payload)
	envelope_.Retries = p.Retries
	p.writeEntity(envelope_)
	return envelope_
}

// FromEntity reads from type entity.Envelope, then writes back to receiver and returns it
func (p *Published) FromEntity(envelope_ *entity.Envelope) *Published {
	if envelope_ == nil {
		return nil
	}
	if p == nil {
		p = new(Published)
	} else {
		*p = Published{}
	}
	p.ID = envelope_.ID
	p.Version = envelope_.Version
	p.Topic = envelope_.Topic
	p.Retries = envelope_.Retries
	p.readEntity(envelope_)
	return p
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (p Published) ShootMap() { /*noop*/ }
