// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package xgorm

import (
	"github.com/lopolopen/shoot"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// NewOptions constructs a new instance of type Options
func NewOptions(schema string, logLevel logger.LogLevel, db *gorm.DB) *Options {
	return &Options{
		Schema:   schema,
		LogLevel: logLevel,
		DB:       db,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Schema is a configuration for the filed Schema
func Schema(schema_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Schema = schema_
	}
}

// LogLevel is a configuration for the filed LogLevel
func LogLevel(logLevel_ logger.LogLevel) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.LogLevel = logLevel_
	}
}

// DB is a configuration for the filed DB
func DB(db_ *gorm.DB) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.DB = db_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Schema = "gap"
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
