// Code generated by "shoot new -json -file=pagination.go"; DO NOT EDIT. (v0.7.1)

package entity

import "encoding/json"

// NewPagination constructs a new instance of type Pagination
func NewPagination(page int, perPage int) *Pagination {
	return &Pagination{
		Page:    page,
		PerPage: perPage,
	}
}

type _json_Pagination struct {
	Page      int `json:"page"`
	PerPage   int `json:"perPage"`
	Total     int `json:"total"`
	TotalPage int `json:"totalPage"`
}

// MarshalJSON serializes type Pagination to json bytes
func (p Pagination) MarshalJSON() ([]byte, error) {
	data := _json_Pagination{
		Page:      p.Page,
		PerPage:   p.PerPage,
		Total:     p.Total,
		TotalPage: p.TotalPage,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Pagination
func (p *Pagination) UnmarshalJSON(data []byte) error {
	var pagination_ _json_Pagination
	if err := json.Unmarshal(data, &pagination_); err != nil {
		return err
	}
	p.Page = pagination_.Page
	p.PerPage = pagination_.PerPage
	p.Total = pagination_.Total
	p.TotalPage = pagination_.TotalPage
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p Pagination) ShootNew() { /*noop*/ }
