// Code generated by "shoot new -getset -json -type=Pagination"; DO NOT EDIT. (v0.7.1)

package entity

import "encoding/json"

// NewPagination constructs a new instance of type Pagination
func NewPagination(page int, perPage int) *Pagination {
	return &Pagination{
		page:    page,
		perPage: perPage,
	}
}

// Page gets the value of field page
func (p *Pagination) Page() int {
	return p.page
}

// PerPage gets the value of field perPage
func (p *Pagination) PerPage() int {
	return p.perPage
}

// SetPage sets the value of field page
func (p *Pagination) SetPage(page_ int) {
	p.page = page_
}

// SetPerPage sets the value of field perPage
func (p *Pagination) SetPerPage(perPage_ int) {
	p.perPage = perPage_
}

type _json_Pagination struct {
	Page      int `json:"page"`
	PerPage   int `json:"perPage"`
	Total     int `json:"total"`
	TotalPage int `json:"totalPage"`
}

// MarshalJSON serializes type Pagination to json bytes
func (p Pagination) MarshalJSON() ([]byte, error) {
	data := _json_Pagination{
		Page:      p.Page(),
		PerPage:   p.PerPage(),
		Total:     p.Total,
		TotalPage: p.TotalPage,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Pagination
func (p *Pagination) UnmarshalJSON(data []byte) error {
	var pagination_ _json_Pagination
	if err := json.Unmarshal(data, &pagination_); err != nil {
		return err
	}
	p.SetPage(pagination_.Page)
	p.SetPerPage(pagination_.PerPage)
	p.Total = pagination_.Total
	p.TotalPage = pagination_.TotalPage
	return nil
}

// PaginationGetter is read-only interface for Pagination type
type PaginationGetter interface {
	Page() int
	PerPage() int
}

// PaginationSetter is write-only interface for Pagination type
type PaginationSetter interface {
	SetPage(int)
	SetPerPage(int)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p Pagination) ShootNew() { /*noop*/ }
