// Code generated by "shoot map -way=-> -path=../../entity -to=Envelope,Envelope -type=Published,Received"; DO NOT EDIT. (v0.7.1)

package gorm

import "github.com/lopolopen/gap/internal/entity"

// ToEntity converts receiver to type entity.Envelope
func (p *Published) ToEntity() *entity.Envelope {
	if p == nil {
		return nil
	}
	envelope_ := new(entity.Envelope)
	envelope_.ID = p.ID
	envelope_.Version = p.Version
	envelope_.Topic = p.Topic
	envelope_.Payload = []byte(p.Payload)
	envelope_.Retries = p.Retries
	p.writeEntity(envelope_)
	return envelope_
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (p Published) ShootMap() { /*noop*/ }
