// Code generated by "shoot map -way=-> -path=../../entity -to=Envelope,Envelope -type=Published,Received"; DO NOT EDIT. (v0.7.1)

package gorm

import "github.com/lopolopen/gap/internal/entity"

// ToEntity converts receiver to type entity.Envelope
func (r *Received) ToEntity() *entity.Envelope {
	if r == nil {
		return nil
	}
	envelope_ := new(entity.Envelope)
	envelope_.ID = r.ID
	envelope_.Version = r.Version
	envelope_.Topic = r.Topic
	envelope_.Payload = []byte(r.Payload)
	envelope_.Retries = r.Retries
	envelope_.Group = r.Group
	r.writeEntity(envelope_)
	return envelope_
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (r Received) ShootMap() { /*noop*/ }
