// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package gap

import (
	"context"
	"runtime"

	"github.com/lopolopen/shoot"
)

// NewOptions constructs a new instance of type Options
func NewOptions(context context.Context, drainContext context.Context, serviceName string, version string, defaultGroup string, claimBatchSize int, maxRetries int, lookbackSeconds int, pumpIntervalSeconds int, maxPublishConcurrency int, workerId int64, storagePlugin PluginOptions, brokerPlugin PluginOptions, publishBufferSize int, workConcurrencyFactor int) *Options {
	return &Options{
		Context:               context,
		DrainContext:          drainContext,
		ServiceName:           serviceName,
		Version:               version,
		DefaultGroup:          defaultGroup,
		ClaimBatchSize:        claimBatchSize,
		MaxRetries:            maxRetries,
		LookbackSeconds:       lookbackSeconds,
		PumpIntervalSeconds:   pumpIntervalSeconds,
		MaxPublishConcurrency: maxPublishConcurrency,
		WorkerID:              workerId,
		StoragePlugin:         storagePlugin,
		BrokerPlugin:          brokerPlugin,
		PublishBufferSize:     publishBufferSize,
		WorkConcurrencyFactor: workConcurrencyFactor,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Context is a configuration for the filed Context
func Context(context_ context.Context) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Context = context_
	}
}

// DrainContext is a configuration for the filed DrainContext
func DrainContext(drainContext_ context.Context) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.DrainContext = drainContext_
	}
}

// ServiceName is a configuration for the filed ServiceName
func ServiceName(serviceName_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.ServiceName = serviceName_
	}
}

// Version is a configuration for the filed Version
func Version(version_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Version = version_
	}
}

// DefaultGroup is a configuration for the filed DefaultGroup
func DefaultGroup(defaultGroup_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.DefaultGroup = defaultGroup_
	}
}

// ClaimBatchSize is a configuration for the filed ClaimBatchSize
func ClaimBatchSize(claimBatchSize_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.ClaimBatchSize = claimBatchSize_
	}
}

// MaxRetries is a configuration for the filed MaxRetries
func MaxRetries(maxRetries_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.MaxRetries = maxRetries_
	}
}

// LookbackSeconds is a configuration for the filed LookbackSeconds
func LookbackSeconds(lookbackSeconds_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.LookbackSeconds = lookbackSeconds_
	}
}

// PumpIntervalSeconds is a configuration for the filed PumpIntervalSeconds
func PumpIntervalSeconds(pumpIntervalSeconds_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PumpIntervalSeconds = pumpIntervalSeconds_
	}
}

// MaxPublishConcurrency is a configuration for the filed MaxPublishConcurrency
func MaxPublishConcurrency(maxPublishConcurrency_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.MaxPublishConcurrency = maxPublishConcurrency_
	}
}

// WorkerID is a configuration for the filed WorkerID
func WorkerID(workerID_ int64) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.WorkerID = workerID_
	}
}

// StoragePlugin is a configuration for the filed StoragePlugin
func StoragePlugin(storagePlugin_ PluginOptions) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.StoragePlugin = storagePlugin_
	}
}

// BrokerPlugin is a configuration for the filed BrokerPlugin
func BrokerPlugin(brokerPlugin_ PluginOptions) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.BrokerPlugin = brokerPlugin_
	}
}

// PublishBufferSize is a configuration for the filed PublishBufferSize
func PublishBufferSize(publishBufferSize_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PublishBufferSize = publishBufferSize_
	}
}

// WorkConcurrencyFactor is a configuration for the filed WorkConcurrencyFactor
func WorkConcurrencyFactor(workConcurrencyFactor_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.WorkConcurrencyFactor = workConcurrencyFactor_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Context = context.Background()
	o.DrainContext = context.Background()
	o.Version = "v1"
	o.DefaultGroup = "default"
	o.ClaimBatchSize = 200
	o.MaxRetries = 30
	o.LookbackSeconds = 180
	o.PumpIntervalSeconds = 1
	o.WorkerID = -1
	o.PublishBufferSize = runtime.GOMAXPROCS(0) * 512
	o.WorkConcurrencyFactor = 1
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
