// Code generated by "shoot new -opt -short -type=HandlerDepsOptions"; DO NOT EDIT. (v0.7.1)

package gap

import (
	"github.com/lopolopen/shoot"
)

// NewHandlerDepsOptions constructs a new instance of type HandlerDepsOptions
func NewHandlerDepsOptions(fileName string, pkgPath string, funcName string) *HandlerDepsOptions {
	return &HandlerDepsOptions{
		FileName: fileName,
		PkgPath:  pkgPath,
		FuncName: funcName,
	}
}

// With initializes this instance using the functional options pattern
func (h *HandlerDepsOptions) With(opts ...shoot.Option[HandlerDepsOptions, *HandlerDepsOptions]) *HandlerDepsOptions {
	for _, opt := range opts {
		opt(h)
	}
	return h
}

// FileName is a configuration for the filed FileName
func FileName(fileName_ string) shoot.Option[HandlerDepsOptions, *HandlerDepsOptions] {
	return func(h *HandlerDepsOptions) {
		h.FileName = fileName_
	}
}

// PkgPath is a configuration for the filed PkgPath
func PkgPath(pkgPath_ string) shoot.Option[HandlerDepsOptions, *HandlerDepsOptions] {
	return func(h *HandlerDepsOptions) {
		h.PkgPath = pkgPath_
	}
}

// FuncName is a configuration for the filed FuncName
func FuncName(funcName_ string) shoot.Option[HandlerDepsOptions, *HandlerDepsOptions] {
	return func(h *HandlerDepsOptions) {
		h.FuncName = funcName_
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (h HandlerDepsOptions) ShootNew() { /*noop*/ }
