// Code generated by "gapc -file=saysvc.go"; DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"examples/gin-kafka-mysql-example/event"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
)

func init() {
	var _svc *SaySvc
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.Resolve(
			gapc.FuncName("service.HandleSomethingSaid"),
			gapc.ResolveType("*SaySvc", func(v *SaySvc) { _svc = v }),
		),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ event.SomethingSaid
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := _svc.HandleSomethingSaid()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			event.SomethingSaid{}.Topic(),
			"examples.gin-kafka-mysql-example",
		),
	)
}
