// Code generated by "shoot new -opt -short -type=Options,QueueOptions"; DO NOT EDIT. (v0.7.0)

package xrabbitmq

import (
	"github.com/lopolopen/shoot"
)

// NewQueueOptions constructs a new instance of type QueueOptions
func NewQueueOptions(durable bool, exclusive bool, autoDelete bool) *QueueOptions {
	return &QueueOptions{
		Durable:    durable,
		Exclusive:  exclusive,
		AutoDelete: autoDelete,
	}
}

// With initializes this instance using the functional options pattern
func (q *QueueOptions) With(opts ...shoot.Option[QueueOptions, *QueueOptions]) *QueueOptions {
	q.SetDefault()
	for _, opt := range opts {
		opt(q)
	}
	return q
}

// Durable is a configuration for the filed Durable
func Durable(durable_ bool) shoot.Option[QueueOptions, *QueueOptions] {
	return func(q *QueueOptions) {
		q.Durable = durable_
	}
}

// Exclusive is a configuration for the filed Exclusive
func Exclusive(exclusive_ bool) shoot.Option[QueueOptions, *QueueOptions] {
	return func(q *QueueOptions) {
		q.Exclusive = exclusive_
	}
}

// AutoDelete is a configuration for the filed AutoDelete
func AutoDelete(autoDelete_ bool) shoot.Option[QueueOptions, *QueueOptions] {
	return func(q *QueueOptions) {
		q.AutoDelete = autoDelete_
	}
}

// SetDefault sets the default values
func (q *QueueOptions) SetDefault() {
	q.Durable = true
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (q QueueOptions) ShootNew() { /*noop*/ }
