// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package dashboard

import "github.com/lopolopen/shoot"

// NewOptions constructs a new instance of type Options
func NewOptions(pathPrefix string, locationPath string) *Options {
	return &Options{
		PathPrefix:   pathPrefix,
		LocationPath: locationPath,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// PathPrefix is a configuration for the filed PathPrefix
func PathPrefix(pathPrefix_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PathPrefix = pathPrefix_
	}
}

// LocationPath is a configuration for the filed LocationPath
func LocationPath(locationPath_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.LocationPath = locationPath_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.PathPrefix = "/dashboard"
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
