// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package dashboard

import (
	"net/http"

	"github.com/lopolopen/shoot"
)

// NewOptions constructs a new instance of type Options
func NewOptions(pathPrefix string, route func(method string, path string, handler http.Handler)) *Options {
	return &Options{
		PathPrefix: pathPrefix,
		Route:      route,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// PathPrefix is a configuration for the filed PathPrefix
func PathPrefix(pathPrefix_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PathPrefix = pathPrefix_
	}
}

// Route is a configuration for the filed Route
func Route(route_ func(method string, path string, handler http.Handler)) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Route = route_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.PathPrefix = "/gap-dashboard"
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
