// Code generated by "gapc -file=main.go"; DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"examples/rabbitmq-gorm-mysql-example/event"
	"time"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
	"gorm.io/gorm"
)

func init() {
	var db_ *gorm.DB
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.Resolve(
			gapc.FuncName("main.handle"),
			gapc.ResolveType("*gorm.DB", func(v *gorm.DB) { db_ = v }),
		),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ time.Time
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := handle(db_)
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			"topic.test",
			"examples.rabbitmq-gorm-mysql-example",
		),
	)
}

func init() {
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ *event.OrderCreated
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := handle2()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			new(event.OrderCreated).Topic(),
			"group.test",
		),
	)
}
