// Code generated by "gapc -file=main.go"; DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
)

func init() {
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ time.Time
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := handle()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			"topic.time.now",
			"examples.kafka-mysql-example",
		),
	)
}
