// Code generated by "gapc -file=greetsvc.go"; DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"examples/fiber-rabbitmq-mysql-example/event"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
)

func init() {
	var _svc *GreetSvc
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.Resolve(
			gapc.FuncName("service.HandleHello"),
			gapc.ResolveType("*GreetSvc", func(v *GreetSvc) { _svc = v }),
		),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ event.Hello
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := _svc.HandleHello()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			event.Hello{}.Topic(),
			"examples.fiber-rabbitmq-mysql-example",
		),
	)
}
