// Code generated by "shoot map -path=../../entity -to=Envelope,Envelope -type=Published,Received"; DO NOT EDIT. (v0.7.1)

package mysql

import "github.com/lopolopen/gap/internal/entity"

// ToEntity converts receiver to type entity.Envelope
func (r *Received) ToEntity() *entity.Envelope {
	if r == nil {
		return nil
	}
	envelope_ := new(entity.Envelope)
	envelope_.ID = r.ID
	envelope_.Version = r.Version
	envelope_.Topic = r.Topic
	envelope_.Payload = []byte(r.Payload)
	envelope_.Retries = r.Retries
	envelope_.Group = r.Group
	r.writeEntity(envelope_)
	return envelope_
}

// FromEntity reads from type entity.Envelope, then writes back to receiver and returns it
func (r *Received) FromEntity(envelope_ *entity.Envelope) *Received {
	if envelope_ == nil {
		return nil
	}
	if r == nil {
		r = new(Received)
	} else {
		*r = Received{}
	}
	r.ID = envelope_.ID
	r.Version = envelope_.Version
	r.Topic = envelope_.Topic
	r.Group = envelope_.Group
	r.Retries = envelope_.Retries
	r.readEntity(envelope_)
	return r
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (r Received) ShootMap() { /*noop*/ }
