// Code generated by "shoot new -opt -short -type=Options,TopicOptions"; DO NOT EDIT. (v0.7.0)

package kafka

import (
	"github.com/lopolopen/shoot"
)

// NewOptions constructs a new instance of type Options
func NewOptions(password string, userName string, topicOpts *TopicOptions) *Options {
	return &Options{
		Password:  password,
		UserName:  userName,
		TopicOpts: topicOpts,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Password is a configuration for the filed Password
func Password(password_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Password = password_
	}
}

// UserName is a configuration for the filed UserName
func UserName(userName_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.UserName = userName_
	}
}

// TopicOpts is a configuration for the filed TopicOpts
func TopicOpts(topicOpts_ *TopicOptions) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.TopicOpts = topicOpts_
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
