// Code generated by "shoot new -opt -short -type=Options,TopicOptions"; DO NOT EDIT. (v0.7.0)

package kafka

import (
	"github.com/lopolopen/shoot"
)

// NewTopicOptions constructs a new instance of type TopicOptions
func NewTopicOptions(numPartitions int, replicationFactor int16) *TopicOptions {
	return &TopicOptions{
		NumPartitions:     numPartitions,
		ReplicationFactor: replicationFactor,
	}
}

// With initializes this instance using the functional options pattern
func (t *TopicOptions) With(opts ...shoot.Option[TopicOptions, *TopicOptions]) *TopicOptions {
	for _, opt := range opts {
		opt(t)
	}
	return t
}

// NumPartitions is a configuration for the filed NumPartitions
func NumPartitions(numPartitions_ int) shoot.Option[TopicOptions, *TopicOptions] {
	return func(t *TopicOptions) {
		t.NumPartitions = numPartitions_
	}
}

// ReplicationFactor is a configuration for the filed ReplicationFactor
func ReplicationFactor(replicationFactor_ int16) shoot.Option[TopicOptions, *TopicOptions] {
	return func(t *TopicOptions) {
		t.ReplicationFactor = replicationFactor_
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (t TopicOptions) ShootNew() { /*noop*/ }
