// Code generated by "shoot new -opt -short -file=options.dependency.go"; DO NOT EDIT. (v0.7.1)

package gap

import "github.com/lopolopen/shoot"

// NewDependencyOptions constructs a new instance of type DependencyOptions
func NewDependencyOptions(fileName string, pkgPath string, funcName string) *DependencyOptions {
	return &DependencyOptions{
		FileName: fileName,
		PkgPath:  pkgPath,
		FuncName: funcName,
	}
}

// With initializes this instance using the functional options pattern
func (d *DependencyOptions) With(opts ...shoot.Option[DependencyOptions, *DependencyOptions]) *DependencyOptions {
	for _, opt := range opts {
		opt(d)
	}
	return d
}

// FileName is a configuration for the filed FileName
func FileName(fileName_ string) shoot.Option[DependencyOptions, *DependencyOptions] {
	return func(d *DependencyOptions) {
		d.FileName = fileName_
	}
}

// PkgPath is a configuration for the filed PkgPath
func PkgPath(pkgPath_ string) shoot.Option[DependencyOptions, *DependencyOptions] {
	return func(d *DependencyOptions) {
		d.PkgPath = pkgPath_
	}
}

// FuncName is a configuration for the filed FuncName
func FuncName(funcName_ string) shoot.Option[DependencyOptions, *DependencyOptions] {
	return func(d *DependencyOptions) {
		d.FuncName = funcName_
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (d DependencyOptions) ShootNew() { /*noop*/ }
