// Code generated by "shoot new -opt -short -type=DIOptions"; DO NOT EDIT. (v0.7.1)

package internal

import (
	"github.com/lopolopen/shoot"
)

// NewDIOptions constructs a new instance of type DIOptions
func NewDIOptions(fileName string, pkgPath string, funcName string) *DIOptions {
	return &DIOptions{
		FileName: fileName,
		PkgPath:  pkgPath,
		FuncName: funcName,
	}
}

// With initializes this instance using the functional options pattern
func (d *DIOptions) With(opts ...shoot.Option[DIOptions, *DIOptions]) *DIOptions {
	for _, opt := range opts {
		opt(d)
	}
	return d
}

// FileName is a configuration for the filed FileName
func FileName(fileName_ string) shoot.Option[DIOptions, *DIOptions] {
	return func(d *DIOptions) {
		d.FileName = fileName_
	}
}

// PkgPath is a configuration for the filed PkgPath
func PkgPath(pkgPath_ string) shoot.Option[DIOptions, *DIOptions] {
	return func(d *DIOptions) {
		d.PkgPath = pkgPath_
	}
}

// FuncName is a configuration for the filed FuncName
func FuncName(funcName_ string) shoot.Option[DIOptions, *DIOptions] {
	return func(d *DIOptions) {
		d.FuncName = funcName_
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (d DIOptions) ShootNew() { /*noop*/ }
