// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package internal

import (
	"context"

	"github.com/lopolopen/shoot"
)

// NewOptions constructs a new instance of type Options
func NewOptions(context context.Context, serviceName string, version string, defaultGroup string, group string, claimBatchSize int, maxRetries int, lookbackSeconds int, pumpingIntervalSeconds int, maxPublishConcurrency int32, workerId int64) *Options {
	return &Options{
		Context:                context,
		ServiceName:            serviceName,
		Version:                version,
		DefaultGroup:           defaultGroup,
		Group:                  group,
		ClaimBatchSize:         claimBatchSize,
		MaxRetries:             maxRetries,
		LookbackSeconds:        lookbackSeconds,
		PumpingIntervalSeconds: pumpingIntervalSeconds,
		MaxPublishConcurrency:  maxPublishConcurrency,
		WorkerID:               workerId,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Context is a configuration for the filed Context
func Context(context_ context.Context) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Context = context_
	}
}

// ServiceName is a configuration for the filed ServiceName
func ServiceName(serviceName_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.ServiceName = serviceName_
	}
}

// Version is a configuration for the filed Version
func Version(version_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Version = version_
	}
}

// DefaultGroup is a configuration for the filed DefaultGroup
func DefaultGroup(defaultGroup_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.DefaultGroup = defaultGroup_
	}
}

// Group is a configuration for the filed Group
func Group(group_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Group = group_
	}
}

// ClaimBatchSize is a configuration for the filed ClaimBatchSize
func ClaimBatchSize(claimBatchSize_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.ClaimBatchSize = claimBatchSize_
	}
}

// MaxRetries is a configuration for the filed MaxRetries
func MaxRetries(maxRetries_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.MaxRetries = maxRetries_
	}
}

// LookbackSeconds is a configuration for the filed LookbackSeconds
func LookbackSeconds(lookbackSeconds_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.LookbackSeconds = lookbackSeconds_
	}
}

// PumpingIntervalSeconds is a configuration for the filed PumpingIntervalSeconds
func PumpingIntervalSeconds(pumpingIntervalSeconds_ int) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PumpingIntervalSeconds = pumpingIntervalSeconds_
	}
}

// MaxPublishConcurrency is a configuration for the filed MaxPublishConcurrency
func MaxPublishConcurrency(maxPublishConcurrency_ int32) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.MaxPublishConcurrency = maxPublishConcurrency_
	}
}

// WorkerID is a configuration for the filed WorkerID
func WorkerID(workerID_ int64) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.WorkerID = workerID_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Context = context.Background()
	o.Version = "v1"
	o.DefaultGroup = "default"
	o.ClaimBatchSize = 200
	o.MaxRetries = 30
	o.LookbackSeconds = 180
	o.PumpingIntervalSeconds = 1
	o.MaxPublishConcurrency = 1
	o.WorkerID = -1
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
