// Code generated by "shoot new -opt -short -type=Options,QueueOptions"; DO NOT EDIT. (v0.7.0)

package rabbitmq

import (
	"github.com/lopolopen/shoot"
)

// NewOptions constructs a new instance of type Options
func NewOptions(password string, userName string, virtualHost string, exchange string, endpoint string, url string, confirmMode bool, queueOpts *QueueOptions) *Options {
	return &Options{
		Password:    password,
		UserName:    userName,
		VirtualHost: virtualHost,
		Exchange:    exchange,
		Endpoint:    endpoint,
		URL:         url,
		ConfirmMode: confirmMode,
		QueueOpts:   queueOpts,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Password is a configuration for the filed Password
func Password(password_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Password = password_
	}
}

// UserName is a configuration for the filed UserName
func UserName(userName_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.UserName = userName_
	}
}

// VirtualHost is a configuration for the filed VirtualHost
func VirtualHost(virtualHost_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.VirtualHost = virtualHost_
	}
}

// Exchange is a configuration for the filed Exchange
func Exchange(exchange_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Exchange = exchange_
	}
}

// Endpoint is a configuration for the filed Endpoint
func Endpoint(endpoint_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Endpoint = endpoint_
	}
}

// URL is a configuration for the filed URL
func URL(url_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.URL = url_
	}
}

// ConfirmMode is a configuration for the filed ConfirmMode
func ConfirmMode(confirmMode_ bool) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.ConfirmMode = confirmMode_
	}
}

// QueueOpts is a configuration for the filed QueueOpts
func QueueOpts(queueOpts_ *QueueOptions) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.QueueOpts = queueOpts_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Password = "guest"
	o.UserName = "guest"
	o.VirtualHost = "/"
	o.Exchange = "default"
	o.Endpoint = "localhost:5672"
	o.QueueOpts = new(QueueOptions).With()
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
