// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package gorm

import (
	"github.com/lopolopen/shoot"
	"gorm.io/gorm/logger"
)

// NewOptions constructs a new instance of type Options
func NewOptions(schema string, logLevel logger.LogLevel, gormDb any, mySql *MySQLConf, postgreSql *PostgreSQLConf) *Options {
	return &Options{
		Schema:     schema,
		LogLevel:   logLevel,
		GormDB:     gormDb,
		MySQL:      mySql,
		PostgreSQL: postgreSql,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Schema is a configuration for the filed Schema
func Schema(schema_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Schema = schema_
	}
}

// LogLevel is a configuration for the filed LogLevel
func LogLevel(logLevel_ logger.LogLevel) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.LogLevel = logLevel_
	}
}

// GormDB is a configuration for the filed GormDB
func GormDB(gormDB_ any) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.GormDB = gormDB_
	}
}

// MySQL is a configuration for the filed MySQL
func MySQL(mySQL_ *MySQLConf) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.MySQL = mySQL_
	}
}

// PostgreSQL is a configuration for the filed PostgreSQL
func PostgreSQL(postgreSQL_ *PostgreSQLConf) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.PostgreSQL = postgreSQL_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Schema = "gap"
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
