// Code generated by "gapc -file=mysvc.go"; DO NOT EDIT.

package service

import (
	"context"
	"encoding/json"
	"examples/rabbitmq-gorm-mysql-example/event"

	"github.com/lopolopen/gap"
	"github.com/lopolopen/gap/gapc"
)

func init() {
	var _svc *MySvc
	gap.Subscribe(
		gapc.GoGenerated(),
		gapc.Resolve(
			gapc.FuncName("service.HandleOrderCreatedEvent"),
			gapc.ResolveType("*MySvc", func(v *MySvc) { _svc = v }),
		),
		gapc.HandleTopicWithinGroupRaw(
			func(ctx context.Context, data_ []byte, headers_ map[string]string) error {
				var msg_ *event.OrderCreated
				err := json.Unmarshal(data_, &msg_)
				if err != nil {
					return err
				}
				handler := _svc.HandleOrderCreatedEvent()
				err = handler(ctx, msg_, headers_)
				if err != nil {
					return err
				}
				return nil
			},
			new(event.OrderCreated).Topic(),
			"examples.rabbitmq-gorm-mysql-example",
		),
	)
}
