// Code generated by "shoot enum -json -type=ExtType"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[None-0]
	_ = x[MySQL-1]
	_ = x[GORM-2]
	_ = x[RabbitMQ-3]
	_ = x[Kafka-4]
}

const _extType_max = None | MySQL | GORM | RabbitMQ | Kafka

var _extType_values = []ExtType{None, MySQL, GORM, RabbitMQ, Kafka}

var _extType_strings = []string{"None", "MySQL", "GORM", "RabbitMQ", "Kafka"}

var _extType_string_map = map[ExtType]string{
	None:     "None",
	MySQL:    "MySQL",
	GORM:     "GORM",
	RabbitMQ: "RabbitMQ",
	Kafka:    "Kafka",
}

var _extType_value_map = map[string]ExtType{
	"None":     None,
	"MySQL":    MySQL,
	"GORM":     GORM,
	"RabbitMQ": RabbitMQ,
	"Kafka":    Kafka,
}

// String returns the string value of type ExtType
func (e ExtType) String() string {
	str, ok := _extType_string_map[e]
	if ok {
		return str
	}
	if e < 0 || e > _extType_max {
		return fmt.Sprintf("%d", e)
	}

	return fmt.Sprintf("%d", e)
}

func (e ExtType) Values() []ExtType {
	return _extType_values
}

func (e ExtType) Strings() []string {
	return _extType_strings
}

func (e ExtType) IsValid() bool {
	_, ok := _extType_string_map[e]
	return ok
}

func (e ExtType) ValueMap() map[string]ExtType {
	return _extType_value_map
}

func (e ExtType) StringMap() map[ExtType]string {
	return _extType_string_map
}

// MarshalJSON implements the json.Marshaler interface for ExtType
func (e ExtType) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ExtType
func (e *ExtType) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ ExtType
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("ExtType enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[ExtType](s_); err != nil {
		return err
	}
	*e = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (e ExtType) ShootEnum() { /*noop*/ }
