// Code generated by "shoot enum -json -type=PluginKind"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[PluginKindSelf-0]
	_ = x[PluginKindStorage-1]
	_ = x[PluginKindBroker-2]
}

const _pluginKind_max = PluginKindSelf | PluginKindStorage | PluginKindBroker

var _pluginKind_values = []PluginKind{PluginKindSelf, PluginKindStorage, PluginKindBroker}

var _pluginKind_strings = []string{"Self", "Storage", "Broker"}

var _pluginKind_string_map = map[PluginKind]string{
	PluginKindSelf:    "Self",
	PluginKindStorage: "Storage",
	PluginKindBroker:  "Broker",
}

var _pluginKind_value_map = map[string]PluginKind{
	"Self":    PluginKindSelf,
	"Storage": PluginKindStorage,
	"Broker":  PluginKindBroker,
}

// String returns the string value of type PluginKind
func (p PluginKind) String() string {
	str, ok := _pluginKind_string_map[p]
	if ok {
		return str
	}
	if p < 0 || p > _pluginKind_max {
		return fmt.Sprintf("%d", p)
	}

	return fmt.Sprintf("%d", p)
}

func (p PluginKind) Values() []PluginKind {
	return _pluginKind_values
}

func (p PluginKind) Strings() []string {
	return _pluginKind_strings
}

func (p PluginKind) IsValid() bool {
	_, ok := _pluginKind_string_map[p]
	return ok
}

func (p PluginKind) ValueMap() map[string]PluginKind {
	return _pluginKind_value_map
}

func (p PluginKind) StringMap() map[PluginKind]string {
	return _pluginKind_string_map
}

// MarshalJSON implements the json.Marshaler interface for PluginKind
func (p PluginKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PluginKind
func (p *PluginKind) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ PluginKind
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("PluginKind enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[PluginKind](s_); err != nil {
		return err
	}
	*p = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (p PluginKind) ShootEnum() { /*noop*/ }
