// Code generated by "shoot enum -json -type=Plugin"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[PluginNone-0]
	_ = x[PluginMySQL-1]
	_ = x[PluginGORM-2]
	_ = x[PluginRabbitMQ-3]
	_ = x[PluginKafka-4]
}

const _plugin_max = PluginNone | PluginMySQL | PluginGORM | PluginRabbitMQ | PluginKafka

var _plugin_values = []Plugin{PluginNone, PluginMySQL, PluginGORM, PluginRabbitMQ, PluginKafka}

var _plugin_strings = []string{"None", "MySQL", "GORM", "RabbitMQ", "Kafka"}

var _plugin_string_map = map[Plugin]string{
	PluginNone:     "None",
	PluginMySQL:    "MySQL",
	PluginGORM:     "GORM",
	PluginRabbitMQ: "RabbitMQ",
	PluginKafka:    "Kafka",
}

var _plugin_value_map = map[string]Plugin{
	"None":     PluginNone,
	"MySQL":    PluginMySQL,
	"GORM":     PluginGORM,
	"RabbitMQ": PluginRabbitMQ,
	"Kafka":    PluginKafka,
}

// String returns the string value of type Plugin
func (p Plugin) String() string {
	str, ok := _plugin_string_map[p]
	if ok {
		return str
	}
	if p < 0 || p > _plugin_max {
		return fmt.Sprintf("%d", p)
	}

	return fmt.Sprintf("%d", p)
}

func (p Plugin) Values() []Plugin {
	return _plugin_values
}

func (p Plugin) Strings() []string {
	return _plugin_strings
}

func (p Plugin) IsValid() bool {
	_, ok := _plugin_string_map[p]
	return ok
}

func (p Plugin) ValueMap() map[string]Plugin {
	return _plugin_value_map
}

func (p Plugin) StringMap() map[Plugin]string {
	return _plugin_string_map
}

// MarshalJSON implements the json.Marshaler interface for Plugin
func (p Plugin) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Plugin
func (p *Plugin) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ Plugin
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("Plugin enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[Plugin](s_); err != nil {
		return err
	}
	*p = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (p Plugin) ShootEnum() { /*noop*/ }
