// Code generated by "shoot enum -json -type=MetaType"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[Self-0]
	_ = x[Storage-1]
	_ = x[Broker-2]
	_ = x[WebFramwork-3]
}

const _metaType_max = Self | Storage | Broker | WebFramwork

var _metaType_values = []MetaType{Self, Storage, Broker, WebFramwork}

var _metaType_strings = []string{"Self", "Storage", "Broker", "WebFramwork"}

var _metaType_string_map = map[MetaType]string{
	Self:        "Self",
	Storage:     "Storage",
	Broker:      "Broker",
	WebFramwork: "WebFramwork",
}

var _metaType_value_map = map[string]MetaType{
	"Self":        Self,
	"Storage":     Storage,
	"Broker":      Broker,
	"WebFramwork": WebFramwork,
}

// String returns the string value of type MetaType
func (m MetaType) String() string {
	str, ok := _metaType_string_map[m]
	if ok {
		return str
	}
	if m < 0 || m > _metaType_max {
		return fmt.Sprintf("%d", m)
	}

	return fmt.Sprintf("%d", m)
}

func (m MetaType) Values() []MetaType {
	return _metaType_values
}

func (m MetaType) Strings() []string {
	return _metaType_strings
}

func (m MetaType) IsValid() bool {
	_, ok := _metaType_string_map[m]
	return ok
}

func (m MetaType) ValueMap() map[string]MetaType {
	return _metaType_value_map
}

func (m MetaType) StringMap() map[MetaType]string {
	return _metaType_string_map
}

// MarshalJSON implements the json.Marshaler interface for MetaType
func (m MetaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MetaType
func (m *MetaType) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ MetaType
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("MetaType enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[MetaType](s_); err != nil {
		return err
	}
	*m = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (m MetaType) ShootEnum() { /*noop*/ }
