// Code generated by "shoot enum -json -type=PluginType"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"encoding/json"
	"fmt"

	"github.com/lopolopen/shoot"
)

func _() {
	var x [1]struct{}
	_ = x[None-0]
	_ = x[MySQL-1]
	_ = x[GORM-2]
	_ = x[RabbitMQ-3]
	_ = x[Kafka-4]
}

const _pluginType_max = None | MySQL | GORM | RabbitMQ | Kafka

var _pluginType_values = []PluginType{None, MySQL, GORM, RabbitMQ, Kafka}

var _pluginType_strings = []string{"None", "MySQL", "GORM", "RabbitMQ", "Kafka"}

var _pluginType_string_map = map[PluginType]string{
	None:     "None",
	MySQL:    "MySQL",
	GORM:     "GORM",
	RabbitMQ: "RabbitMQ",
	Kafka:    "Kafka",
}

var _pluginType_value_map = map[string]PluginType{
	"None":     None,
	"MySQL":    MySQL,
	"GORM":     GORM,
	"RabbitMQ": RabbitMQ,
	"Kafka":    Kafka,
}

// String returns the string value of type PluginType
func (p PluginType) String() string {
	str, ok := _pluginType_string_map[p]
	if ok {
		return str
	}
	if p < 0 || p > _pluginType_max {
		return fmt.Sprintf("%d", p)
	}

	return fmt.Sprintf("%d", p)
}

func (p PluginType) Values() []PluginType {
	return _pluginType_values
}

func (p PluginType) Strings() []string {
	return _pluginType_strings
}

func (p PluginType) IsValid() bool {
	_, ok := _pluginType_string_map[p]
	return ok
}

func (p PluginType) ValueMap() map[string]PluginType {
	return _pluginType_value_map
}

func (p PluginType) StringMap() map[PluginType]string {
	return _pluginType_string_map
}

// MarshalJSON implements the json.Marshaler interface for PluginType
func (p PluginType) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PluginType
func (p *PluginType) UnmarshalJSON(data []byte) error {
	var s_ string
	var v_ PluginType
	var err error
	if err = json.Unmarshal(data, &s_); err != nil {
		return fmt.Errorf("PluginType enum should be a string, got %s", data)
	}
	if v_, err = shoot.ParseEnum[PluginType](s_); err != nil {
		return err
	}
	*p = v_
	return nil
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (p PluginType) ShootEnum() { /*noop*/ }
