// Code generated by "shoot enum -sql -gorm -type=Status"; DO NOT EDIT. (v0.7.1)

package enum

import (
	"database/sql/driver"
	"errors"
	"fmt"

	"github.com/lopolopen/shoot"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func _() {
	var x [1]struct{}
	_ = x[StatusPending-1]
	_ = x[StatusProcessing-2]
	_ = x[StatusSucceeded-3]
	_ = x[StatusFailed-(-1)]
}

const _status_max = StatusPending | StatusProcessing | StatusSucceeded | StatusFailed

var _status_values = []Status{StatusPending, StatusProcessing, StatusSucceeded, StatusFailed}

var _status_strings = []string{"Pending", "Processing", "Succeeded", "Failed"}

var _status_string_map = map[Status]string{
	StatusPending:    "Pending",
	StatusProcessing: "Processing",
	StatusSucceeded:  "Succeeded",
	StatusFailed:     "Failed",
}

var _status_value_map = map[string]Status{
	"Pending":    StatusPending,
	"Processing": StatusProcessing,
	"Succeeded":  StatusSucceeded,
	"Failed":     StatusFailed,
}

// String returns the string value of type Status
func (s Status) String() string {
	str, ok := _status_string_map[s]
	if ok {
		return str
	}
	if s < 0 || s > _status_max {
		return fmt.Sprintf("%d", s)
	}

	return fmt.Sprintf("%d", s)
}

func (s Status) Values() []Status {
	return _status_values
}

func (s Status) Strings() []string {
	return _status_strings
}

func (s Status) IsValid() bool {
	_, ok := _status_string_map[s]
	return ok
}

func (s Status) ValueMap() map[string]Status {
	return _status_value_map
}

func (s Status) StringMap() map[Status]string {
	return _status_string_map
}

// Value implements the driver.Valuer interface for Status
func (s Status) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan implements the driver.Scanner interface for Status
func (s *Status) Scan(value interface{}) error {
	data, ok := value.([]byte)
	if !ok {
		return errors.New("bad enum type")
	}
	e_, err := shoot.ParseEnum[Status](string(data))
	if err != nil {
		return err
	}
	*s = e_
	return nil
}

// GormDataType specifies the general data type that GORM should treat this field as.
func (s Status) GormDataType() string {
	return "string"
}

// GormDBDataType provides the exact database column type definition for this field.
func (s Status) GormDBDataType(db *gorm.DB, field *schema.Field) string {
	return "ENUM('Pending','Processing','Succeeded','Failed')"
}

// ShootEnum exists solely to fulfill the EnumShooter interface contract
func (s Status) ShootEnum() { /*noop*/ }
