// Code generated by "shoot new -opt -short -type=Options"; DO NOT EDIT. (v0.7.1)

package mysql

import "github.com/lopolopen/shoot"

// NewOptions constructs a new instance of type Options
func NewOptions(schema string, dsn string) *Options {
	return &Options{
		Schema: schema,
		DSN:    dsn,
	}
}

// With initializes this instance using the functional options pattern
func (o *Options) With(opts ...shoot.Option[Options, *Options]) *Options {
	o.SetDefault()
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Schema is a configuration for the filed Schema
func Schema(schema_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.Schema = schema_
	}
}

// DSN is a configuration for the filed DSN
func DSN(dsn_ string) shoot.Option[Options, *Options] {
	return func(o *Options) {
		o.DSN = dsn_
	}
}

// SetDefault sets the default values
func (o *Options) SetDefault() {
	o.Schema = "gap"
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Options) ShootNew() { /*noop*/ }
